### ISSUE TITLE
Display web page version

### ISSUE THREAD

**Issue by ammgws** [fiberpunk1/NodeWebPage#1]
Currently there doesn't seem to be a way to see which version of the webpage is installed. 

EDIT:
There doesn't seem to be any version info or tag releases in this repo in the first place, and the webpage is also included in the firmware repo too: https://github.com/fiberpunk1/Beam-ESP32/tree/main/Webpage

How does development work? Is this the man repo, and changes are synced to the firmware repo at FW release time?

**Comment by fiber-punk** [comment]
added webpage version today.

"How does development work? Is this the man repo, and changes are synced to the firmware repo at FW release time?"
I plan that the ESP firmware of Node will no longer contain the webpage, and the webpage will be dominated by this repo.
